[project]
name = "genai-document-portal"
version = "0.1.0"
description = "End to end LLMOps project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "python-dotenv>=1.2.1",
]
